version: '3.7'

x-common: &common
  build: .
  working_dir: /app
  ports:
      - "8000:8000"


# Services not meant to be started all at once
# see the run_test.py for details

services:
  flask_marshmallow_uvicorn:
    <<: *common
    entrypoint: uvicorn main:app --host 0.0.0.0 --workers ${WORKERS}
  
  drf_uvicorn:
    <<: *common
    entrypoint: uvicorn drf.wsgi:application --host 0.0.0.0 --workers ${WORKERS}

  ninja_uvicorn:
    <<: *common
    entrypoint: uvicorn djninja.wsgi:application --host 0.0.0.0 --workers ${WORKERS}

  drf_gunicorn:
    <<: *common
    entrypoint: gunicorn drf.wsgi:application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_gunicorn:
    <<: *common
    entrypoint: gunicorn djninja.wsgi:application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers ${WORKERS}

  ninja_asgi:
    <<: *common
    entrypoint: uvicorn djninja.asgi:application --host 0.0.0.0 --workers ${WORKERS}

  network_service:
    build: .
    entrypoint: python network_service.py > /dev/null
